### ISSUE TITLE
Installer Error: No such file or directory

### ISSUE THREAD

**Issue by johnallen3d** [koraktor/mestral#4] opened 2013-05-13 22:08 UTC
Just ran the install script ande received an error. Here's the output from my install.

``` sh
❯ ruby -e "$(curl -fLsS https://raw.github.com/mestral/mestral/install/install.rb)"
Cloning the Mestral repository to '/usr/local/mestral'
remote: Counting objects: 348, done.
remote: Compressing objects: 100% (201/201), done.
remote: Total 348 (delta 137), reused 344 (delta 133)
Receiving objects: 100% (348/348), 94.29 KiB, done.
Resolving deltas: 100% (137/137), done.
remote: Counting objects: 7468, done.
remote: Compressing objects: 100% (4057/4057), done.
remote: Total 7468 (delta 3657), reused 7044 (delta 3261)
Receiving objects: 100% (7468/7468), 2.56 MiB | 1000 KiB/s, done.
Resolving deltas: 100% (3657/3657), done.
-e:56:in `stat': No such file or directory - /usr/local/heroku/bin (Errno::ENOENT)
    from -e:56:in `block in <main>'
    from -e:55:in `select'
    from -e:55:in `<main>'
```

Not sure why /usr/local/heroku would be involved.

**Comment by koraktor** [comment] 2013-05-13 22:18
Seems like that directory is in your `PATH` variable, but does no longer exist. To work around this, you should remove it from `PATH`. But the problem should be fixed in the install script.

**Comment by johnallen3d** [comment] 2013-05-13 23:42
You nailed it. Darn Heroku Toolbelt added a line to my .zshenv to prepend with that path. Cleaned that up and the install script completes successfully now. Thanks!

**Comment by koraktor** [comment] 2013-05-14 04:43
Reopening this until the problem is fixed in the install script.

**Closed as completed** 2013-05-14 04:56 UTC
